version: '3.8'

services:
  front-end:
    container_name: react_app
    build: ./frontend
    ports:
      - 3000:3000

  postgres-db:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back-end:
    container_name: springboot_app
    build: ./backend
    # command to execute shell script
    entrypoint: sh -c "chmod +x /springboot_app/entrypoint.sh && sh /springboot_app/entrypoint.sh"
    ports:
      - 8080
    depends_on:
      - postgres-db

volumes:
  postgres_data: